### ISSUE TITLE
[Bug report] Component does not work if the icon has multiple paths

### ISSUE THREAD

**Issue by ericcornelissen** [sh7dm/vue-simple-icons#11]
**Describe the bug**
If an icon is constructed of multiple `<path>`s, vue-simple-icons will only use the first `<path>`. Take for example the [Travis CI icon](http://simpleicons.org/?q=travis%20ci).

**Steps To Reproduce**
1. Add (or replace) `<vue-simple-icon name="Travis CI" />` to `playground/src/App.vue`.
2. Run `$ yarn dev`
3. See the result at `localhost:8080`

**Expected behavior**
vue-simple-icons should use all paths found in the SVG provided by SimpleIcons.

**Screenshots**
![image](https://user-images.githubusercontent.com/3742559/50080239-53239680-01f4-11e9-93a7-4ca73f573f81.png)

_The first one should be the Travis CI icon_

**Additional context**
The problem is clearly caused by the constructions used in the `render` method for the component as seen here:

https://github.com/sh7dm/vue-simple-icons/blob/ba97f994dd4fe8eb596a6f47ca289388fcb5de77/src/VueSimpleIcon.ts#L8-L23

**Comment by sh7dm** [comment]
Compatibility: https://caniuse.com/#search=DOMParser. @ericcornelissen thanks for your bug report!
