### ISSUE TITLE
[Suggestion] Do not set stroke color on path

### ISSUE THREAD

**Issue by ericcornelissen** [sh7dm/vue-simple-icons#8]
As per the [Contributing Guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#5-check-the-icon) of SimpleIcons, SVGs should never rely on a `stroke`. Hence, I think we should consider **not** [settings the stroke color](https://github.com/sh7dm/vue-simple-icons/blob/ba97f994dd4fe8eb596a6f47ca289388fcb5de77/src/VueSimpleIcon.ts#L19) on the `<path>` of the icon.

**Comment by sh7dm** [comment]
@ericcornelissen Thanks for your contribution!
